## NumPy

In [1]:
import numpy as np

In [2]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

⬆︎ファイル名が見れる

## NumPy Arrays(ndarray)

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [7]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
type(matrix[0][0])

numpy.int64

In [11]:
type(1)

int

numpyのint64というデータ構造ということがわかる。
numpy独自のデータタイプであることを理解しよう

In [14]:
ndarray = np.array([1, 2, 3], dtype=np.uint8)

uint8 = unsigned + - integer 8bit
つまり、負の値を持たない2の8乗 0~255までの値である。

In [15]:
ndarray = np.array([1, 2, 3], dtype=np.float32)

In [16]:
ndarray

array([1., 2., 3.], dtype=float32)

In [17]:
ndarray.astype(np.uint8) # データタイプを変更することができる

array([1, 2, 3], dtype=uint8)

## ndarrayの演算(Broadcasting)

In [18]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [19]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

numpyのarrayは各要素毎の値を足した値になる

In [20]:
a = [1,2,3]
b = [1,2,3]
a + b

[1, 2, 3, 1, 2, 3]

In [22]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

## Shape

In [24]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
ndarray.shape

(3, 2)

ndarrayを作成した時はshapeで確認すること。
(行、列)の要素数が表示される

In [26]:
ndarray.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])

In [31]:
print(ndarray1.shape) # 1次元

(3,)


In [38]:
print(ndarray2.shape) # 2次元

(1, 3)


### 次元を増やす

In [33]:
np.expand_dims(ndarray1, axis=0) # (3,) -> (1, 3)と次元を増やすことができる

array([[1, 2, 3]])

In [36]:
np.expand_dims(ndarray1, axis=1) # (3,) -> (3, 1)に変更になる

array([[1],
       [2],
       [3]])

In [41]:
expand_ndarray = np.expand_dims(ndarray1, axis=-1) # 最後の値の次元を増やす
print(expand_ndarray)

[[1]
 [2]
 [3]]


### 次元を減らす

In [48]:
np.squeeze(expand_ndarray) # サイズが1の次元がすべて削除された形状(shape)を返す

array([1, 2, 3])

In [44]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ndarray.shape

(3, 3)

In [46]:
ndarray.flatten() # 1次元に戻す

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## IndexingとSlicing

In [49]:
ndarray = np.array([1, 2, 3, 4])

In [50]:
ndarray

array([1, 2, 3, 4])

In [52]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
ndarray[0, 1] # 0行めの1行目を取得することができる

2

In [56]:
ndarray = np.array([1, 2, 3, 4])
ndarray

array([1, 2, 3, 4])

In [58]:
ndarray[1:3]

array([2, 3])

In [60]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
ndarray[:3, 2:] # 行の3未満、列の2以上の値を取得できる

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

## np.arange(),np.linspace(),np.logspace()

In [68]:
np.arange(0, 5, 1) # arrange(start, stop, step)

array([0, 1, 2, 3, 4])

In [69]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [71]:
np.linspace(0, 10, 5) # linspace(start, stop, 要素数)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [72]:
np.logspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

## 行列生成(zeros, ones, eye)

In [73]:
shape = (3, 4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
np.zeros(3)

array([0., 0., 0.])

ndarrayの要素をあらかじめ作っておいて、配列に値を入れておく時に使う

In [75]:
shape = (5, 4)
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [76]:
np.ones(3)

array([1., 1., 1.])

In [77]:
np.ones((5, 4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


## np.randomを使って乱数生成

In [82]:
np.random.rand()

0.4006678070578139

In [118]:
# randoの前に、seedを定義することですべて同じ値になる。
np.random.seed(0)
a = np.random.rand()
np.random.seed(0)
b = np.random.rand()
np.random.seed(0)
c = np.random.rand()
print(a)
print(b)
print(c)

0.5488135039273248
0.5488135039273248
0.5488135039273248


In [93]:
np.random.randn(2, 3)

array([[-0.85990661,  1.77260763, -1.11036305],
       [ 0.18121427,  0.56434487, -0.56651023]])

In [94]:
np.random.normal()

0.7299755964138446

In [101]:
a = np.random.randint(1, 10)
b = np.random.randint(1, 100, (2, 3))
print(a)
print(b)

8
[[ 4 71 22]
 [50 58  4]]


In [106]:
a = [1, 2, 3, 4, 5]
np.random.choice(a)

4

## 統計量を求める

In [119]:
std_normal = np.random.randn(5, 5)
std_normal

array([[ 0.74159174,  1.55291372, -2.2683282 ,  1.33354538, -0.84272405],
       [ 1.96992445,  1.26611853, -0.50587654,  2.54520078,  1.08081191],
       [ 0.48431215,  0.57914048, -0.18158257,  1.41020463, -0.37447169],
       [ 0.27519832, -0.96075461,  0.37692697,  0.03343893,  0.68056724],
       [-1.56349669, -0.56669762, -0.24214951,  1.51439128, -0.3330574 ]])

In [120]:
# 最大値
std_normal.max()

2.5452007784710537

In [121]:
# 最小値
std_normal.min()

-2.268328201180374

In [124]:
# 最大値のindexを取得
max_index = std_normal.argmax()
std_normal.flatten()[max_index] # max_indexの値は、flattenした場合のインデックス番号

2.5452007784710537

In [125]:
# 平均値を取得
std_normal.mean()

0.32020590513139313

In [127]:
# 中央値
np.median(std_normal)

0.37692697499528294

In [128]:
# 標準偏差を取得
np.std(std_normal)

1.1132549590492968

In [129]:
a = std_normal.max(axis=0) # 列毎の最大値を求める
b = std_normal.max(axis=1) # 行毎の最大値を求めr
print(a)
print(b)

[1.96992445 1.55291372 0.37692697 2.54520078 1.08081191]
[1.55291372 2.54520078 1.41020463 0.68056724 1.51439128]


## 数学で使う便利関数

In [130]:
# 平方根 square root
np.sqrt([1, 2, 3, 4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [134]:
# log
x = np.linspace(1, 10, 10)
print(x)
np.log(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [137]:
# 指数関数 Exponential function
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [138]:
# ネイピア数
np.e

2.718281828459045

In [142]:
# 合計 (sumation)
array = np.arange(1, 11)
np.sum([1, 2, 3])

6

In [144]:
print(array)
np.sum(array)

[ 1  2  3  4  5  6  7  8  9 10]


55

In [146]:
ndarray = array.reshape(2, 5)
ndarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [147]:
np.sum(ndarray, axis=1)

array([15, 40])

In [148]:
# 絶対値 absolute value
array = np.arange(-10, 0)
array

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [149]:
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## np.nanとnp.isnan()

In [150]:
# NaN : Not a Number

In [151]:
np.nan

nan

In [153]:
np.isnan(np.log(-100)) # nanかどうかチェックする関数

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


True

## その他の便利関数

### np.clip()

In [154]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
np.clip(array, 3, 7) # 最小値と最大を設定できる

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [156]:
1e-4

0.0001

## numpy arrayのcondition

In [157]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.where

In [175]:
# whereはこの使い方がメジャー
np.where(array > 3, 10, 0) # trueのものは0に置き換え。falseのものは10に置き換え

array([ 0,  0,  0,  0, 10,  0, 10])

In [161]:
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

In [162]:
# filter
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [163]:
array[array>3]

array([4, 5, 6, 7, 8, 9])

In [165]:
ndarray = array.reshape(2, 5)
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [166]:
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

In [167]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [168]:
(ndarray > 3).all()

False

In [169]:
# 1つでもTrue?
(ndarray > 3).any()

True

In [170]:
(ndarray > 3).all(axis=0)

array([False, False, False, False,  True])

### np.unique()

In [171]:
array = np.array([1, 1, 2, 3, 4, 2, 4])
array

array([1, 1, 2, 3, 4, 2, 4])

In [172]:
np.unique(array)

array([1, 2, 3, 4])

In [173]:
np.unique(array, return_counts=True) # 重複してる値とその数を返してくれる

(array([1, 2, 3, 4]), array([2, 2, 1, 2]))

### np.bincount()

In [174]:
np.bincount(array)

array([0, 2, 2, 1, 2])

## np.concatenate()とnp.stack()

In [177]:
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [179]:
ndarray_odd = np.arange(1, 19, 2).reshape(3, 3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [180]:
np.concatenate([ndarray_even, ndarray_odd])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [206]:
np.stack([ndarray_even, ndarray_odd], axis=-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [207]:
stacked_array = _

In [208]:
stacked_array.shape

(3, 3, 2)

### np.transpose.T shapeの行と列の値を反転してくれる

In [210]:
ndarray = np.random.randn(3, 4)
ndarray

array([[ 0.63973599, -0.38586334, -0.77576235,  0.99571135],
       [-1.93320478,  0.24853063, -0.03124534, -0.13947396],
       [-0.19065598,  0.44863753, -0.99242977, -0.22593966]])

In [211]:
ndarray.shape

(3, 4)

In [212]:
np.transpose(ndarray)

array([[ 0.63973599, -1.93320478, -0.19065598],
       [-0.38586334,  0.24853063,  0.44863753],
       [-0.77576235, -0.03124534, -0.99242977],
       [ 0.99571135, -0.13947396, -0.22593966]])

In [213]:
transpose_ndarray = _

In [214]:
transpose_ndarray.shape

(4, 3)

In [216]:
rand_arr = np.random.randn(5, 4, 3)
rand_arr

array([[[-1.65457077e+00, -6.39722638e-01, -4.79419801e-01],
        [ 3.11363503e-01, -7.76020467e-01, -3.07364810e-01],
        [-3.66523941e-01,  1.11971196e+00, -4.57922420e-01],
        [ 4.25393398e-01, -2.79711835e-02,  1.47598983e+00]],

       [[ 6.46780097e-01, -3.64334312e-01, -6.78777389e-01],
        [-3.53627856e-01, -7.40747471e-01, -6.75021832e-01],
        [-1.32784256e-01,  6.19801063e-01,  1.79116846e+00],
        [ 1.71000438e-01, -1.72567135e+00,  1.60658540e-01]],

       [[-8.58985321e-01, -2.06420942e-01,  4.88426467e-01],
        [-8.38330966e-01,  3.81163744e-01, -9.90903282e-01],
        [ 1.01788005e+00,  3.41587396e-01, -1.25088622e+00],
        [ 9.25250752e-01, -9.04786158e-01,  1.84369153e+00]],

       [[ 1.52550724e+00, -1.44553558e+00,  3.77160611e-01],
        [-7.05572292e-02,  6.04159707e-01,  4.72148998e-01],
        [ 8.19917293e-01,  9.07519617e-01, -5.85822875e-01],
        [ 9.37558842e-01, -2.54608092e-01,  9.73598712e-01]],

       [[ 2.0728

In [217]:
np.transpose(rand_arr)

array([[[-1.65457077e+00,  6.46780097e-01, -8.58985321e-01,
          1.52550724e+00,  2.07282772e-01],
        [ 3.11363503e-01, -3.53627856e-01, -8.38330966e-01,
         -7.05572292e-02,  6.06389001e-01],
        [-3.66523941e-01, -1.32784256e-01,  1.01788005e+00,
          8.19917293e-01,  1.87239408e+00],
        [ 4.25393398e-01,  1.71000438e-01,  9.25250752e-01,
          9.37558842e-01,  1.03081595e+00]],

       [[-6.39722638e-01, -3.64334312e-01, -2.06420942e-01,
         -1.44553558e+00,  1.09964197e+00],
        [-7.76020467e-01, -7.40747471e-01,  3.81163744e-01,
          6.04159707e-01,  1.76084071e-03],
        [ 1.11971196e+00,  6.19801063e-01,  3.41587396e-01,
          9.07519617e-01, -2.41073590e-01],
        [-2.79711835e-02, -1.72567135e+00, -9.04786158e-01,
         -2.54608092e-01, -1.27698899e+00]],

       [[-4.79419801e-01, -6.78777389e-01,  4.88426467e-01,
          3.77160611e-01,  9.39896981e-01],
        [-3.07364810e-01, -6.75021832e-01, -9.90903282e-01,


## np.save('path',array)とnp.load('path')

In [219]:
ndarray = np.random.randn(3, 4, 5)
ndarray.shape

(3, 4, 5)

In [220]:
np.save('sample_ndarray.npy', ndarray)

In [222]:
loaded_ndarray = np.load('sample_ndarray.npy')
loaded_ndarray.shape

(3, 4, 5)

In [223]:
dictionary = {
    'id': 123456,
    'IMAGE': ndarray
}

In [226]:
np.save('sample_dict.npy', dictionary)

In [233]:
# 取得した値は、({})のarrayで返ってくる。
lioaded_dict = np.load('sample_dict.npy', allow_pickle=True)

In [234]:
a = np.array({'a': 1})

In [232]:
a[()] # arrayからオブジェクトの形にしたい場合は、この取得方法。

{'a': 1}