In [9]:
1 + 1

2

In [10]:
1 + 4

5

## header

In [11]:
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

In [ ]:
np_array = np.array([[[1, 2,1], [3, 4,1], [5, 6,1]], [[1, 2,1], [3, 4,1], [5, 6,1]]])
np.expand_dims(np_array, axis=-1)
np_array

array([[[1, 2, 1],
        [3, 4, 1],
        [5, 6, 1]],

       [[1, 2, 1],
        [3, 4, 1],
        [5, 6, 1]]])

In [ ]:
np_array.shape

(2, 3, 3)

In [ ]:
np_array = np.arange(0, 20, 1)
np_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a = np_array.reshape(4, 5)
b = np.expand_dims(a, axis=1)
b

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19]]])

In [ ]:
b.shape

(4, 1, 5)

In [ ]:
print(124)

: 

In [ ]:
print(1234)

In [ ]:
data = {
    'Name': 'John',
    'Sex': 'male',
    'Age': 22
}

In [ ]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [ ]:
data = {
  'id': [1, 2, 3, 4, 5],
  'name': ['taku', 'ume', 'kazu', 'kina', 'naka'],
  'gender': ['female', 'female', 'female', 'female', 'female',]
}

In [ ]:
df = pd.DataFrame(data)
df

NameError: name 'pd' is not defined